=== TheChirag356/ori-ui/src/lib/scripts/schema/registry.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"type": "object",
	"properties": {
		"$schema": {
			"type": "string"
		},
		"name": {
			"type": "string"
		},
		"homepage": {
			"type": "string"
		},
		"overrideDependencies": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"aliases": {
			"type": "object",
			"properties": {
				"lib": {
					"type": "string"
				},
				"ui": {
					"type": "string"
				},
				"components": {
					"type": "string"
				},
				"utils": {
					"type": "string"
				},
				"hooks": {
					"type": "string"
				}
			},
			"additionalProperties": false
		},
		"items": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					"title": {
						"type": "string"
					},
					"type": {
						"type": "string",
						"enum": [
							"registry:file",
							"registry:page",
							"registry:ui",
							"registry:component",
							"registry:lib",
							"registry:hook",
							"registry:theme",
							"registry:style",
							"registry:block",
							"registry:example",
							"registry:internal"
						]
					},
					"author": {
						"type": "string",
						"minLength": 2
					},
					"description": {
						"type": "string"
					},
					"dependencies": {
						"type": "array",
						"items": {
							"type": "string"
						}
					},
					"devDependencies": {
						"type": "array",
						"items": {
							"type": "string"
						}
					},
					"registryDependencies": {
						"type": "array",
						"items": {
							"type": "string"
						}
					},
					"meta": {
						"type": "object",
						"propertyNames": {
							"type": "string"
						},
						"additionalProperties": {}
					},
					"files": {
						"type": "array",
						"items": {
							"type": "object",
							"properties": {
								"content": {
									"type": "string"
								},
								"type": {
									"type": "string",
									"enum": [
										"registry:file",
										"registry:page",
										"registry:ui",
										"registry:component",
										"registry:lib",
										"registry:hook",
										"registry:theme",
										"registry:style"
									]
								},
								"target": {
									"type": "string"
								},
								"path": {
									"type": "string"
								}
							},
							"required": [
								"type",
								"path"
							],
							"additionalProperties": false
						}
					},
					"cssVars": {
						"type": "object",
						"properties": {
							"theme": {
								"type": "object",
								"propertyNames": {
									"type": "string"
								},
								"additionalProperties": {
									"type": "string"
								}
							},
							"light": {
								"type": "object",
								"propertyNames": {
									"type": "string"
								},
								"additionalProperties": {
									"type": "string"
								}
							},
							"dark": {
								"type": "object",
								"propertyNames": {
									"type": "string"
								},
								"additionalProperties": {
									"type": "string"
								}
							}
						},
						"additionalProperties": false
					},
					"css": {
						"$ref": "#/$defs/__schema0"
					}
				},
				"required": [
					"name",
					"type",
					"registryDependencies",
					"files"
				],
				"additionalProperties": false
			}
		}
	},
	"required": [
		"name",
		"homepage",
		"items"
	],
	"additionalProperties": false,
	"$defs": {
		"__schema0": {
			"type": "object",
			"propertyNames": {
				"type": "string"
			},
			"additionalProperties": {
				"anyOf": [
					{
						"type": "string"
					},
					{
						"$ref": "#/$defs/__schema0"
					}
				]
			}
		}
	}
}

=== TheChirag356/ori-ui/registry.json
{
  "$schema": "https://shadcn-svelte.com/schema/registry.json",
  "name": "Ori UI",
  "homepage": "https://www.oriui.app",
  "aliases": {
    "lib": "$lib",
    "components": "$lib/components",
    "utils": "$lib/utils/utils",
    "ui": "$lib/components/ui",
    "hooks": "$lib/hooks"
  },
  "items": [
    {
      "name": "copy-button",
      "type": "registry:block",
      "title": "Copy Button",
      "description": "",
      "registryDependencies": [
        "button"
      ],
      "dependencies": [],
      "files": [
        {
          "path": "src/lib/registry/buttons/copy-button/copy-button.svelte",
          "type": "registry:file",
          "target": "ori/copy-button/copy-button.svelte"
        },
        {
          "path": "src/lib/registry/buttons/copy-button/index.ts",
          "type": "registry:file",
          "target": "ori/copy-button/index.ts"
        },
        {
          "path": "src/lib/registry/buttons/copy-button/meta.json",
          "type": "registry:file",
          "target": "ori/copy-button/meta.json"
        }
      ],
      "author": "Chirag Arora <arorachirag12005@gmail.com>",
      "meta": {
        "author": "TheChirag356",
        "version": "1.0.0",
        "documentation": "https://www.oriui.app/components/copy-button",
        "repository": "https://github.com/TheChirag356/ori-ui"
      }
    },
    {
      "name": "interactive-hover-button",
      "type": "registry:block",
      "title": "Interactive Hover Button",
      "description": "",
      "registryDependencies": [],
      "dependencies": [
        "@tabler/icons-svelte"
      ],
      "files": [
        {
          "path": "src/lib/registry/buttons/interactive-hover-button/index.ts",
          "type": "registry:file",
          "target": "ori/interactive-hover-button/index.ts"
        },
        {
          "path": "src/lib/registry/buttons/interactive-hover-button/interactive-hover-button.svelte",
          "type": "registry:file",
          "target": "ori/interactive-hover-button/interactive-hover-button.svelte"
        },
        {
          "path": "src/lib/registry/buttons/interactive-hover-button/meta.json",
          "type": "registry:file",
          "target": "ori/interactive-hover-button/meta.json"
        }
      ],
      "author": "Chirag Arora <arorachirag12005@gmail.com>",
      "meta": {
        "author": "TheChirag356",
        "version": "1.0.0",
        "documentation": "https://www.oriui.app/components/interactive-hover-button",
        "repository": "https://github.com/TheChirag356/ori-ui"
      }
    },
    {
      "name": "ios-toggle-button",
      "type": "registry:block",
      "title": "Ios Toggle Button",
      "description": "",
      "registryDependencies": [],
      "dependencies": [],
      "files": [
        {
          "path": "src/lib/registry/buttons/ios-toggle-button/index.ts",
          "type": "registry:file",
          "target": "ori/ios-toggle-button/index.ts"
        },
        {
          "path": "src/lib/registry/buttons/ios-toggle-button/ios-toggle-button.svelte",
          "type": "registry:file",
          "target": "ori/ios-toggle-button/ios-toggle-button.svelte"
        },
        {
          "path": "src/lib/registry/buttons/ios-toggle-button/meta.json",
          "type": "registry:file",
          "target": "ori/ios-toggle-button/meta.json"
        }
      ],
      "author": "Chirag Arora <arorachirag12005@gmail.com>",
      "meta": {
        "author": "TheChirag356",
        "version": "1.0.0",
        "documentation": "https://www.oriui.app/components/ios-toggle-button",
        "repository": "https://github.com/TheChirag356/ori-ui"
      }
    },
    {
      "name": "liquid-button",
      "type": "registry:block",
      "title": "Liquid Button",
      "description": "",
      "registryDependencies": [
        "button"
      ],
      "dependencies": [
        "tailwind-variants"
      ],
      "files": [
        {
          "path": "src/lib/registry/buttons/liquid-button/index.ts",
          "type": "registry:file",
          "target": "ori/liquid-button/index.ts"
        },
        {
          "path": "src/lib/registry/buttons/liquid-button/liquid-button.svelte",
          "type": "registry:file",
          "target": "ori/liquid-button/liquid-button.svelte"
        },
        {
          "path": "src/lib/registry/buttons/liquid-button/meta.json",
          "type": "registry:file",
          "target": "ori/liquid-button/meta.json"
        }
      ],
      "author": "Chirag Arora <arorachirag12005@gmail.com>",
      "meta": {
        "author": "TheChirag356",
        "version": "1.0.0",
        "documentation": "https://www.oriui.app/components/liquid-button",
        "repository": "https://github.com/TheChirag356/ori-ui"
      }
    },
    {
      "name": "moving-border-button",
      "type": "registry:block",
      "title": "Moving Border Button",
      "description": "",
      "registryDependencies": [
        "button"
      ],
      "dependencies": [],
      "files": [
        {
          "path": "src/lib/registry/buttons/moving-border-button/index.ts",
          "type": "registry:file",
          "target": "ori/moving-border-button/index.ts"
        },
        {
          "path": "src/lib/registry/buttons/moving-border-button/meta.json",
          "type": "registry:file",
          "target": "ori/moving-border-button/meta.json"
        },
        {
          "path": "src/lib/registry/buttons/moving-border-button/moving-border-button.svelte",
          "type": "registry:file",
          "target": "ori/moving-border-button/moving-border-button.svelte"
        }
      ],
      "author": "Chirag Arora <arorachirag12005@gmail.com>",
      "meta": {
        "author": "TheChirag356",
        "version": "1.0.0",
        "documentation": "https://www.oriui.app/components/moving-border-button",
        "repository": "https://github.com/TheChirag356/ori-ui"
      }
    },
    {
      "name": "pulsating-button",
      "type": "registry:block",
      "title": "Pulsating Button",
      "description": "",
      "registryDependencies": [
        "button"
      ],
      "dependencies": [],
      "files": [
        {
          "path": "src/lib/registry/buttons/pulsating-button/index.ts",
          "type": "registry:file",
          "target": "ori/pulsating-button/index.ts"
        },
        {
          "path": "src/lib/registry/buttons/pulsating-button/meta.json",
          "type": "registry:file",
          "target": "ori/pulsating-button/meta.json"
        },
        {
          "path": "src/lib/registry/buttons/pulsating-button/pulsating-button.svelte",
          "type": "registry:file",
          "target": "ori/pulsating-button/pulsating-button.svelte"
        }
      ],
      "author": "Chirag Arora <arorachirag12005@gmail.com>",
      "meta": {
        "author": "TheChirag356",
        "version": "1.0.0",
        "documentation": "https://www.oriui.app/components/pulsating-button",
        "repository": "https://github.com/TheChirag356/ori-ui"
      }
    },
    {
      "name": "rainbow-button",
      "type": "registry:block",
      "title": "Rainbow Button",
      "description": "",
      "registryDependencies": [
        "button"
      ],
      "dependencies": [],
      "files": [
        {
          "path": "src/lib/registry/buttons/rainbow-button/index.ts",
          "type": "registry:file",
          "target": "ori/rainbow-button/index.ts"
        },
        {
          "path": "src/lib/registry/buttons/rainbow-button/meta.json",
          "type": "registry:file",
          "target": "ori/rainbow-button/meta.json"
        },
        {
          "path": "src/lib/registry/buttons/rainbow-button/rainbow-button.svelte",
          "type": "registry:file",
          "target": "ori/rainbow-button/rainbow-button.svelte"
        }
      ],
      "author": "Chirag Arora <arorachirag12005@gmail.com>",
      "meta": {
        "author": "TheChirag356",
        "version": "1.0.0",
        "documentation": "https://www.oriui.app/components/rainbow-button",
        "repository": "https://github.com/TheChirag356/ori-ui"
      }
    },
    {
      "name": "ripple-button",
      "type": "registry:block",
      "title": "Ripple Button",
      "description": "",
      "registryDependencies": [
        "button"
      ],
      "dependencies": [],
      "files": [
        {
          "path": "src/lib/registry/buttons/ripple-button/index.ts",
          "type": "registry:file",
          "target": "ori/ripple-button/index.ts"
        },
        {
          "path": "src/lib/registry/buttons/ripple-button/meta.json",
          "type": "registry:file",
          "target": "ori/ripple-button/meta.json"
        },
        {
          "path": "src/lib/registry/buttons/ripple-button/ripple-button.svelte",
          "type": "registry:file",
          "target": "ori/ripple-button/ripple-button.svelte"
        }
      ],
      "author": "Chirag Arora <arorachirag12005@gmail.com>",
      "meta": {
        "author": "TheChirag356",
        "version": "1.0.0",
        "documentation": "https://www.oriui.app/components/ripple-button",
        "repository": "https://github.com/TheChirag356/ori-ui"
      }
    },
    {
      "name": "slide-text-button",
      "type": "registry:block",
      "title": "Slide Text Button",
      "description": "",
      "registryDependencies": [
        "button"
      ],
      "dependencies": [],
      "files": [
        {
          "path": "src/lib/registry/buttons/slide-text-button/index.ts",
          "type": "registry:file",
          "target": "ori/slide-text-button/index.ts"
        },
        {
          "path": "src/lib/registry/buttons/slide-text-button/meta.json",
          "type": "registry:file",
          "target": "ori/slide-text-button/meta.json"
        },
        {
          "path": "src/lib/registry/buttons/slide-text-button/slide-text-button.svelte",
          "type": "registry:file",
          "target": "ori/slide-text-button/slide-text-button.svelte"
